# SPDX-FileCopyrightText: 2022 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: build
on: push

jobs:

  build:
    runs-on: windows-2019
    steps:

    - name: checkout repository
      uses: actions/checkout@v3

    - name: enable Native Tools Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: build Milton
      run: ./build.bat

    - name: create artifact
      uses: actions/upload-artifact@v3
      with:
        name: milton
        path: |
          build/milton.exe
          build/Carlito.*
